#!/bin/sh

set -e

FILE=$1
[ -f "${FILE}" ] || { echo 'Syntax is '$0' FILE.'; exit 1; }
HFILE=$( echo "${FILE}" | sed 's/.md/.html/g' )

which python || { echo "No Python."; exit 1; }
{
cat <<EOF
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/flatly/bulmaswatch.min.css">
    </head>
    <body>
        <section class="section">
            <div class="content">
EOF

python -m markdown -x mdx_mathjax -x codehilite -x sane_lists -x md_mermaid -x tables -- "${FILE}"

cat <<EOF
            </div>
        </section>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
	<script src="https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js"></script>
        <script src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
                 messageStyle: "none",
                 tex2jax: {
                     preview: "none"
                 }
            });
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"></script>
    </body>
</html>
EOF
} > "${HFILE}"

PFILE=$( echo "${HFILE}" | sed 's/.html/.pdf/g' )
TMPDIR=${TMPDIR:-${TEMP}}
TMPDIR=${TMPDIR:-${TMP}}
TMPDIR=${TMPDIR:-.}

which phantomjs || { echo "No PhantomJS."; exit 1; }
{
cat <<EOF
var sys = require('system');
var page = require('webpage').create();
page.settings.dpi = "120";
page.paperSize = {
    format: 'letter',
    orientation: 'portrait',
};
page.open(sys.args[1], function() {
    setTimeout(function() {
      page.render(sys.args[2]);
      phantom.exit();
    }, 25);
});
EOF
} > "${TMPDIR}/phantom-script.js"
phantomjs "${TMPDIR}/phantom-script.js" "${HFILE}" "${PFILE}"
rm -f "${TMPDIR}/phantom-script.js"